---
title: "IFEBY310 Syllabus"
---

<!-- [**Télécharger  "PDF du syllabus"**](/documents/ma15y030-syllabus.pdf) -->


::: {.callout-note}

## Organization 


We will have one weeky lecture. Each lecture is organized around [Slides](slides-listings.qmd) and [Notebooks](notebooks-listings.qmd). We will switch from blackboard to laptop and back. You are invited to bring your laptop to the lectures. 


|           | Day       | Hour              | Room                       |  Start |
|:---------:|:-----------:|:-------------------:|:--------------------------------|:--------|
| Lecture     | Friday  | 15:45  - 17:46  | Sophie Germain 014 | 2025-01-17 |

### [{{< fa cal >}}](https://edt.math.univ-paris-diderot.fr/#/parcours/mathinfo/m1)

{{< fa hand-point-right >}} We will not attempt to complete the notebooks during the sessions. You are expected to complete the noteboks on your own time. Solutions (at least partial solutions) are available on the course website.

You can fork the [course repository](https://github.com/s-v-b/IFEBY310) and post issues, comments, and corrections.




:::

::: {.callout-note}

## Objectives


{{< include _objectives_ifeby310.qmd >}}

:::



::: {.callout-note}


### Communication  {{< fa bullhorn >}}

Course  material:   [s-v-b.github.io/IFEBY310](https://s-v-b.github.io/IFEBY310) Fork the repo, use github issues to send feedback (no email please)

Alerts are spread through [Moodle](https://moodle.u-paris.fr/course/view.php?id=28534)

Register at [Moodle portal](https://moodle.u-paris.fr/course/view.php?id=28534) to be updated 

:::

::: {.callout-note}

### [Computing environment](/course-support.html) {{< fa bullhorn >}}

{{< fa database >}} We use the PostGreSQL server from UFR de Mathématiques. To obtain an ENT account  {{< fa user-secret >}} follow procedure  [Moodle](https://moodle.u-paris.fr/course/view.php?id=28534)

{{< fa laptop-code >}} You may install and use 

- [`Python`](https://www.python.org)
- [`Jupyter`](https://jupyter.org)
- [`Pandas`](https://pandas.pydata.org)
- [`Numpy`](https://numpy.org)
- [`Scipy`](https://www.scipy.org)
- [`Plotly`](https://plotly.com)
- [`Altair`](https://altair-viz.github.io)
- [`Dask`](https://dask.org)
- [`Spark`](https://spark.apache.org)
- [`Parquet`](https://parquet.apache.org)
- ['Arrow'](https://arrow.apache.org)
- [`Docker`](https://www.docker.com)
- [`Quarto`](https://www.quarto.org)
- [`R`](https://www.r-project.org)
- [`psql`](https://www.postgresql.org/docs/current/app-psql.html)
- [`VS Code`](https://code.visualstudio.com)

:::


::: {.callout-note}


## Références  {{< fa book >}}

- [Pandas Book](https://wesmckinney.com/book/)
- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)
- [Dask](https://tutorial.dask.org)
- [Spark](https://spark.apache.org/docs/latest/index.html)
- [Data pipelines](https://www.oreilly.com/library/view/data-pipelines-pocket/9781492087823/)
- [Data pipelines](https://www.dataengineeringpodcast.com)
- [Alice](http://webdam.inria.fr/Alice/)
- [Documentation PostGres](https://www.postgresql.org/docs/current/)
- [Next Generation Databases NoSQLand Big Data, Guy Harrison ](https://link.springer.com/book/10.1007/978-1-4842-1329-2)
- [Guy Harrison Blog](https://www.guyharrison.net)
- [Databases trends and applications](https://www.dbta.com)
- [Upcoming book “Principles of Databases”, by Marcelo Arenas, Pablo Barcelo, Leonid Libkin, Wim Martens, and Andreas Pieris.](https://github.com/pdm-book/community)
- 
:::


::: {.callout-note}

### Courses {{< fa chalkboard-teacher >}}

[slides](/slides-listings.qmd) 

[Notebooks](/notebooks-listings.qmd) (html and ipynb)

<!-- [Corrected notebooks](/corriges-tds.qmd) (html and ipynb) -->

:::

::: {.callout-important}

### Evaluation   {{< fa graduation-cap >}}


- Two homeworks/projects

- Grading

:::

::: {.callout-tip}

### {{< fa wizard >}} Trucs 

- Have a look at slides before the course
- Don't jump to corrections
- Use online help (StackOverflow, ChatGPT, copilot, ...)
- Read error messages

:::


::: {.callout-warning}

### Code of conduct

**TL;DR: No cheating!**

:::

 

::: {.callout-important}

### Save the dates !  {{< fa calendar >}}

-   **January 17:** Course kick-off
-   **February 14:** *No session* 
-   **February 28:** Winter Holidays
-   **March 7:** Session 6
-   **April 4:** Room 2017
-   **April 18:** Eastern Holidays
-   **April 25:** Eastern Holidays
-   **May 2:** Session 12
   

[Université Paris Cité calendar](https://u-paris.fr/calendrier-universitaire/) 

[M1 MIDS calendar](https://edt.math.univ-paris-diderot.fr/#/parcours/mathinfo/m1) 

:::


::: {.callout-note}

## [Université Paris Cité](https://u-paris.fr)

Useful links:

- [Charte Université Paris Cité](https://u-paris.fr/valeurs/)
- [Démarches et accessibilité](https://u-paris.fr/demarches-administratives-de-scolarite/)
- [Centre de contact](https://u-paris.fr/centre-de-contact/)
- [Relais handicap](https://u-paris.fr/etudes-et-handicap/)

:::
