---
title: "Week 1"
subtitle: "Introduction"
editor: source
draft: false
---

::: callout-important

-   Room: Halle 166E 
-   Monday 12 January 2026  10h45-12h45
-   {{< fa cal >}} [Calendar](https://edt.math.univ-paris-diderot.fr/#/parcours/mathinfo/m1)

:::


## Lecture : slides

We went (rapidly) through the two decks of slides :

- {{< fa display >}} [Introduction to Big Data](/core/slides/slides01_introduction){target="_blank"}
- {{< fa display >}} [Python Data Science Stack](/core/slides/slides02_python_ds_stack.html){target="_blank"} 

We shall come back to the description of `Spark` in a couple of weeks

During the next two weeks, we shall explore the Python Data Stack. 



## Notebooks

- {{< fa brands python >}} <a href="https://s-v-b.github.io/IFEBY310/core/ipynb/notebook01_python.ipynb" download>Jupyter notebook I : tour of Python</a> 
- {{< fa globe >}} [html: tour of Python](/core/notebooks/notebook01_python.html)  

- {{< fa brands python >}} <a href="https://s-v-b.github.io/IFEBY310/core/ipynb/notebook02_numpy.ipynb" download>Jupyter notebook II : tour of NumPy</a> 
- {{< fa globe >}} [html: tour of NumPy](/core/notebooks/notebook02_numpy.html) 

- {{< fa brands python >}} <a href="https://s-v-b.github.io/IFEBY310/core/ipynb/notebook02-2_numpy.ipynb" download>Jupyter notebook II bis: NumPy Broadcasting</a> 
- {{< fa globe >}} [html: NumPy Broadcasting](/core/notebooks/notebook02-2_numpy.html) 


## References 

You can watch the  Introduction to NumPy conference presented at [EuroSciPy 2023](https://euroscipy.org)

{{< video https://www.youtube.com/embed/8v3u6cydeoY >}}


## Logistics

{{< fa bullhorn >}} To work the `jupyter` notebooks, install `python 3`, 
and modules related to `jupyter`: `jupyter-cache`, `jupyter_client`,
`jupyter_core`, `jupyterlab_widgets` (this induces the installation of dependencies).

<https://jupyter.org>

Download the jupyter notebooks from  [notebooks listings](/notebooks-listings.qmd). 

{{< fa bullhorn >}} If you do not already have an ENT account, follow instructions on  [Moodle](https://moodle.u-paris.fr/course/view.php?id=28534) to get  one. You shall need this account to connect to  PostGres cluster.

<br><br>

::: {style="font-size: 0.875em;"}
Back to [Agenda](/slides-listings.qmd) ⏎
:::
